<a href="https://colab.research.google.com/github/Eshwar2916/Generative-Ai-2025/blob/main/lab_7_2_gen_ai_2303A52377.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Load Dataset
dataset_url = "https://drive.google.com/uc?id=1AcdENlVm5dccNyo_vgdMbneX8YVvH5R3"
df = pd.read_csv(dataset_url)

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Convert categorical columns to numeric using LabelEncoder
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le  # Save encoders for deployment

# Separate features and target
y = df.iloc[:, -1].values  # Last column as target
X = df.iloc[:, :-1].values  # All other columns as features

# Normalize Features
scaler = StandardScaler()
X = scaler.fit_transform(X)
# Split dataset into Training and Testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build ANN Model with specified architecture
model = Sequential([
    Dense(10, activation='tanh', input_shape=(X_train.shape[1],)),  # Hidden Layer 1
    Dense(15, activation='tanh'),  # Hidden Layer 2
    Dense(20, activation='tanh'),  # Hidden Layer 3
    Dense(10, activation='tanh'),  # Hidden Layer 4
    Dense(5, activation='tanh'),   # Hidden Layer 5
    Dense(1, activation='sigmoid')  # Output Layer for binary classification
])

# Compile Model
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Train Model
model.fit(X_train, y_train, epochs=250, batch_size=32, validation_data=(X_test, y_test), verbose=1)

# Save Model
model.save("diabetes_ann_model.h5")

# Predict on Training and Test Data
y_pred_train = (model.predict(X_train) > 0.5).astype(int)
y_pred_test = (model.predict(X_test) > 0.5).astype(int)

# Calculate Performance Metrics
train_acc = accuracy_score(y_train, y_pred_train)
test_acc = accuracy_score(y_test, y_pred_test)
conf_matrix = confusion_matrix(y_test, y_pred_test)
report = classification_report(y_test, y_pred_test)
# Display Results
print(f"\nTraining Accuracy: {train_acc:.4f}")
print(f"Testing Accuracy: {test_acc:.4f}")
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(report)

# Load the Model for Deployment
loaded_model = keras.models.load_model("diabetes_ann_model.h5")

# Function to Predict Diabetes
def predict_diabetes(input_data):
    """
    This function takes a raw input data row, processes it, and predicts diabetes.
    """
    input_data = np.array(input_data).reshape(1, -1)  # Ensure correct shape
    input_scaled = scaler.transform(input_data)  # Apply Standard Scaling
    prediction = loaded_model.predict(input_scaled)[0, 0]
    return "Diabetic" if prediction > 0.5 else "Non-Diabetic"

# Example Prediction
sample_patient = X_test[0]  # Get a sample from test data
prediction_result = predict_diabetes(sample_patient)
print(f"\nPredicted Diagnosis: {prediction_result}")


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 7s 99ms/step - accuracy: 0.3147 - loss: 0.6979 - val_accuracy: 0.3394 - val_loss: 0.6111
Epoch 2/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.3902 - loss: 0.5835 - val_accuracy: 0.3945 - val_loss: 0.4928
Epoch 3/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.4117 - loss: 0.4788 - val_accuracy: 0.4128 - val_loss: 0.3748
Epoch 4/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3980 - loss: 0.4071 - val_accuracy: 0.3761 - val_loss: 0.2618
Epoch 5/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.3909 - loss: 0.3094 - val_accuracy: 0.3945 - val_loss: 0.1605
Epoch 6/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4259 - loss: 0.1923 - val_accuracy: 0.3578 - val_loss: 0.0724
Epoch 7/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4350 - loss: 0.1180 - val_accuracy: 0.3578 - val_loss: 0.0083
Epoch 8/250
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4474 - loss: 0.0254 - val_accuracy: 0.34

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step 
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step 

Training Accuracy: 0.5321
Testing Accuracy: 0.3761

Confusion Matrix:
[[ 8 21  0]
 [ 6 33  0]
 [ 4 37  0]]

Classification Report:
              precision    recall  f1-score   support

           0       0.44      0.28      0.34        29
           1       0.36      0.85      0.51        39
           2       0.00      0.00      0.00        41

    accuracy                           0.38       109
   macro avg       0.27      0.37      0.28       109
weighted avg       0.25      0.38      0.27       109



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step

Predicted Diagnosis: Diabetic
